# fly.toml app configuration file generated for rs-1986 on 2025-10-05T17:48:07+04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rs-1986'
primary_region = 'gru'

[build]
  builder = 'paketobuildpacks/builder:base'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
